### PR TITLE
update the url of `Map your Open Source Career`

### PR DESCRIPTION
**Pull request by donhui**

### CODE REVIEW

**Review by Aaron-Junker — APPROVED** [review]
Goid catch!

**Review by emmairwin — APPROVED** [review]
thanks very much for this21

**Comment by 252775980** [comment]
[Ament.txt](https://github.com/microsoft/OSPO-Courses/files/10739174/Ament.txt)

**Review by 252775980 — COMMENTED** [review]
can you please help me to get fixed may proplem salt

**Comment by 252775980** [comment]
pc

**Pull request merged**
